import type { Metadata } from "next";
import "./globals.css";
import { MaterialProvider } from "./mui/MaterialProvider";



export const metadata: Metadata = {
  title: "Demo Trello",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode
}>) {

return (
<html lang="en">
<body style={{backgroundColor: "#026aa7"}}>
 <MaterialProvider>
  {children}
  </MaterialProvider>
</body>
</html>
)
}
